### ISSUE TITLE
ShowGlyphFocus for italic angle

### ISSUE THREAD

**Issue by Yorlmar** [mekkablue/ShowGlyphFocus#1]
Hi @mekkablue have you thought about including in a new version that works with the italic angle? For me it is very useful especially when spacing, since you have a clearer vision of the size of the inclined box. Many thanks for all the glyphs tools!

**Comment by mekkablue** [comment]
Good point. Will take a look.

**Comment by RafalBuchner** [comment]
italic angle should be respected from now on
